---
# tasks file for samba

- name: Gather os specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: vars

- name: Ensure required packages are installed
  package:
    name: "{{ samba_packages }}"
    state: present

- name: Manage samba configuration
  template:
    src: "smb.conf.j2"
    dest: "{{ samba_config }}"
    mode: 0644
    owner: root
    group: root
  notify:
    - restart samba
